import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — ScholarX" },
      { name: "description", content: "The terms and conditions for using ScholarX." },
      { property: "og:title", content: "Terms of Service — ScholarX" },
      { property: "og:description", content: "The terms and conditions for using ScholarX." },
      { property: "og:url", content: "https://scholarx.space/terms" },
    ],
    links: [{ rel: "canonical", href: "https://scholarx.space/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border px-6 py-4 flex items-center justify-between max-w-4xl mx-auto">
        <Link to="/" className="flex items-center gap-2 font-display font-semibold text-lg">
          <span
            className="inline-flex h-7 w-7 items-center justify-center rounded-lg text-primary-foreground text-xs font-bold"
            style={{ background: "var(--gradient-primary)" }}
          >
            S
          </span>
          ScholarX
        </Link>
        <Link to="/" className="text-sm text-muted-foreground hover:text-foreground transition">
          ← Back home
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold mb-2" style={{ fontFamily: "var(--font-display)" }}>
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: May 15, 2026</p>

        <section className="space-y-8 text-sm leading-relaxed text-foreground/90">
          <div>
            <h2 className="text-lg font-semibold mb-2" style={{ fontFamily: "var(--font-display)" }}>
              1. Acceptance of Terms
            </h2>
            <p>
              By creating an account or using ScholarX ("Service"), you agree to be bound by these Terms of Service.
              If you do not agree, do not use the Service.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-2" style={{ fontFamily: "var(--font-display)" }}>
              2. Intended Use
            </h2>
            <p>
              ScholarX is an AI-powered study tool designed to help students understand concepts and build knowledge.
              It is intended to support learning — not to complete assignments on a student's behalf in violation of
              their school's academic integrity policies. You are responsible for how you use AI-generated content.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-2" style={{ fontFamily: "var(--font-display)" }}>
              3. Account Eligibility
            </h2>
            <p>
              You must be at least 13 years old to use ScholarX. If you are under 18, you represent that a parent
              or guardian has reviewed and agreed to these terms on your behalf.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-2" style={{ fontFamily: "var(--font-display)" }}>
              4. Prohibited Conduct
            </h2>
            <ul className="list-disc list-inside space-y-1 text-muted-foreground">
              <li>Attempting to reverse-engineer or scrape the Service.</li>
              <li>Submitting illegal, harmful, or abusive content.</li>
              <li>Sharing account credentials with others.</li>
              <li>Using the Service to generate misleading or harmful material.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-2" style={{ fontFamily: "var(--font-display)" }}>
              5. AI-Generated Content
            </h2>
            <p>
              Responses generated by the AI are provided for educational purposes only. ScholarX makes no guarantees
              about the accuracy or completeness of AI-generated content. Always verify important information with
              authoritative sources and your instructors.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-2" style={{ fontFamily: "var(--font-display)" }}>
              6. Service Availability
            </h2>
            <p>
              We strive to maintain uptime but do not guarantee uninterrupted access. We may update, modify, or
              discontinue the Service at any time with reasonable notice.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-2" style={{ fontFamily: "var(--font-display)" }}>
              7. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, ScholarX shall not be liable for any indirect, incidental, or
              consequential damages arising from your use of the Service.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-2" style={{ fontFamily: "var(--font-display)" }}>
              8. Changes to Terms
            </h2>
            <p>
              We may update these terms from time to time. Continued use of the Service after changes constitutes
              acceptance of the updated terms.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-2" style={{ fontFamily: "var(--font-display)" }}>
              9. Contact
            </h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a
                href="mailto:support@scholarx.app"
                className="text-primary underline underline-offset-2 hover:opacity-80"
              >
                support@scholarx.app
              </a>
              .
            </p>
          </div>
        </section>
      </main>

      <footer className="border-t border-border mt-16 px-6 py-6 text-center text-xs text-muted-foreground">
        <div className="flex items-center justify-center gap-4">
          <Link to="/privacy" className="hover:text-foreground transition">Privacy Policy</Link>
          <span>·</span>
          <Link to="/terms" className="hover:text-foreground transition">Terms of Service</Link>
          <span>·</span>
          <span>© {new Date().getFullYear()} ScholarX</span>
        </div>
      </footer>
    </div>
  );
}
