/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudyRouteImport } from './routes/study'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupConfirmedRouteImport } from './routes/auth.signup-confirmed'
import { Route as AuthPasswordResetSuccessRouteImport } from './routes/auth.password-reset-success'
import { Route as AuthEmailChangedRouteImport } from './routes/auth.email-changed'
import { Route as AuthEmailChangePendingRouteImport } from './routes/auth.email-change-pending'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupConfirmedRoute = AuthSignupConfirmedRouteImport.update({
  id: '/auth/signup-confirmed',
  path: '/auth/signup-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordResetSuccessRoute =
  AuthPasswordResetSuccessRouteImport.update({
    id: '/auth/password-reset-success',
    path: '/auth/password-reset-success',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthEmailChangedRoute = AuthEmailChangedRouteImport.update({
  id: '/auth/email-changed',
  path: '/auth/email-changed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailChangePendingRoute = AuthEmailChangePendingRouteImport.update({
  id: '/auth/email-change-pending',
  path: '/auth/email-change-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/flashcards': typeof FlashcardsRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/study': typeof StudyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-change-pending': typeof AuthEmailChangePendingRoute
  '/auth/email-changed': typeof AuthEmailChangedRoute
  '/auth/password-reset-success': typeof AuthPasswordResetSuccessRoute
  '/auth/signup-confirmed': typeof AuthSignupConfirmedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/flashcards': typeof FlashcardsRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/study': typeof StudyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-change-pending': typeof AuthEmailChangePendingRoute
  '/auth/email-changed': typeof AuthEmailChangedRoute
  '/auth/password-reset-success': typeof AuthPasswordResetSuccessRoute
  '/auth/signup-confirmed': typeof AuthSignupConfirmedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/flashcards': typeof FlashcardsRoute
  '/graph': typeof GraphRoute
  '/login': typeof LoginRoute
  '/planner': typeof PlannerRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/study': typeof StudyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/tests': typeof TestsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/email-change-pending': typeof AuthEmailChangePendingRoute
  '/auth/email-changed': typeof AuthEmailChangedRoute
  '/auth/password-reset-success': typeof AuthPasswordResetSuccessRoute
  '/auth/signup-confirmed': typeof AuthSignupConfirmedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/flashcards'
    | '/graph'
    | '/login'
    | '/planner'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/research'
    | '/reset-password'
    | '/study'
    | '/support'
    | '/terms'
    | '/tests'
    | '/auth/callback'
    | '/auth/email-change-pending'
    | '/auth/email-changed'
    | '/auth/password-reset-success'
    | '/auth/signup-confirmed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/flashcards'
    | '/graph'
    | '/login'
    | '/planner'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/research'
    | '/reset-password'
    | '/study'
    | '/support'
    | '/terms'
    | '/tests'
    | '/auth/callback'
    | '/auth/email-change-pending'
    | '/auth/email-changed'
    | '/auth/password-reset-success'
    | '/auth/signup-confirmed'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/flashcards'
    | '/graph'
    | '/login'
    | '/planner'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/research'
    | '/reset-password'
    | '/study'
    | '/support'
    | '/terms'
    | '/tests'
    | '/auth/callback'
    | '/auth/email-change-pending'
    | '/auth/email-changed'
    | '/auth/password-reset-success'
    | '/auth/signup-confirmed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GraphRoute: typeof GraphRoute
  LoginRoute: typeof LoginRoute
  PlannerRoute: typeof PlannerRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ResearchRoute: typeof ResearchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudyRoute: typeof StudyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TestsRoute: typeof TestsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthEmailChangePendingRoute: typeof AuthEmailChangePendingRoute
  AuthEmailChangedRoute: typeof AuthEmailChangedRoute
  AuthPasswordResetSuccessRoute: typeof AuthPasswordResetSuccessRoute
  AuthSignupConfirmedRoute: typeof AuthSignupConfirmedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup-confirmed': {
      id: '/auth/signup-confirmed'
      path: '/auth/signup-confirmed'
      fullPath: '/auth/signup-confirmed'
      preLoaderRoute: typeof AuthSignupConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password-reset-success': {
      id: '/auth/password-reset-success'
      path: '/auth/password-reset-success'
      fullPath: '/auth/password-reset-success'
      preLoaderRoute: typeof AuthPasswordResetSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email-changed': {
      id: '/auth/email-changed'
      path: '/auth/email-changed'
      fullPath: '/auth/email-changed'
      preLoaderRoute: typeof AuthEmailChangedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email-change-pending': {
      id: '/auth/email-change-pending'
      path: '/auth/email-change-pending'
      fullPath: '/auth/email-change-pending'
      preLoaderRoute: typeof AuthEmailChangePendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FlashcardsRoute: FlashcardsRoute,
  GraphRoute: GraphRoute,
  LoginRoute: LoginRoute,
  PlannerRoute: PlannerRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ResearchRoute: ResearchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudyRoute: StudyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TestsRoute: TestsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthEmailChangePendingRoute: AuthEmailChangePendingRoute,
  AuthEmailChangedRoute: AuthEmailChangedRoute,
  AuthPasswordResetSuccessRoute: AuthPasswordResetSuccessRoute,
  AuthSignupConfirmedRoute: AuthSignupConfirmedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
